project:
  type: website
website:
  title: Data Cleaning
  navbar:
    background: primary
    search: true
    left:
      - text: "Introduction"
        file: Introduction.html
      - text: "Data Gathering"
        file: Data Gathering.html
      - text: "Data Cleaning"
        file: Data Cleaning qmd.html
      - text: "Exploring Data"
        file: Exploring-Data-rmd.html
      - text: "Naive Bayes"
        file: Naive-Bayes-R.html
      - text: "Decision Trees"
        file: decision_tree_record_data.html
      - text: "SVM"
        file: svm_text_data.html
      - text: "Clustering"
        file: clustering.html
      - text: "ARM and Networking"
        file: ARM.html
